const puppeteer=require('puppeteer'); const fs=require('fs'); const path=require('path');
const BASE=process.argv[2]; const MIRROR=path.join(__dirname,'mirror');
const map=u=>{if(u.includes('react-dom.production'))return'react-dom.production.min.js';if(u.includes('react.production'))return'react.production.min.js';if(u.includes('echarts'))return'echarts.min.js';return null;};
(async()=>{const b=await puppeteer.launch({headless:'new',args:['--no-sandbox','--disable-dev-shm-usage']});const p=await b.newPage();
await p.setViewport({width:1440,height:900});
const errs=[];p.on('console',m=>{if(m.type()==='error')errs.push(m.text().slice(0,200));});p.on('pageerror',e=>errs.push('PAGEERROR '+e.message.slice(0,200)));
await p.setRequestInterception(true);
p.on('request',r=>{const f=map(r.url());if(f){r.respond({status:200,headers:{'access-control-allow-origin':'*'},contentType:'application/javascript',body:fs.readFileSync(path.join(MIRROR,f))});}else if(r.url().includes('fonts.goog')||r.url().includes('gstatic')){r.abort();}else r.continue();});
const apis=[];p.on('response',r=>{if(r.url().includes('/api/'))apis.push(r.url().split('/api/')[1]+' -> '+r.status());});
await p.goto(BASE+'/',{waitUntil:'load',timeout:60000});
await p.waitForFunction(()=>{const e=document.querySelector('.pill-live');return e&&/live data/i.test(e.textContent);},{timeout:30000});
await p.waitForFunction(()=>typeof window.echarts!=='undefined',{timeout:10000}).catch(()=>{});
await p.evaluate(()=>{const b=[...document.querySelectorAll('.sidenav-item')].find(x=>x.textContent.trim().toLowerCase().startsWith('timeline'));b&&b.click();});
await new Promise(r=>setTimeout(r,2500));
const dom=await p.evaluate(()=>{const tl=[...document.querySelectorAll('*')].find(e=>e.className&&(''+e.className).includes('echart'));return{page_active_btn:document.querySelector('.sidenav-item.active')?.textContent.trim(),canvases:document.querySelectorAll('canvas').length,echartDivs:document.querySelectorAll('[class*=echart],[class*=chart]').length,bodyHasTimeline:/Plays|timeline/i.test(document.body.innerText)};});
console.log('DOM after click:',JSON.stringify(dom));
console.log('API calls:',JSON.stringify(apis));
console.log('ERRORS:',errs.length?errs.join('\n'):'(none)');
await b.close();})().catch(e=>console.error('ERR',e.message));
