"""Generate web/data/library.js from tracks.jsonl + scrobbles.jsonl.

The static fallback the dashboard loads before FastAPI responds — for the
file:// workflow (double-click index.html) and as an offline snapshot.
Re-run whenever tracks.jsonl changes. Output is gitignored (personal data).

    python scripts/generate_library_js.py
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT   = Path(__file__).resolve().parent.parent
# Make the repo importable when run directly: `python scripts/generate_library_js.py`
sys.path.insert(0, str(REPO_ROOT))
from pipeline.schema import read_jsonl

TRACKS_PATH   = REPO_ROOT / "tracks.jsonl"
SCROBBLES_PATH = REPO_ROOT / "scrobbles.jsonl"
OUTPUT_PATH   = REPO_ROOT / "web" / "data" / "library.js"


def _aggregate_scrobbles(rows: list[dict]) -> dict:
    by_hour:   list[int] = [0] * 24
    by_dow:    list[int] = [0] * 7
    by_season: dict[str, int] = {"winter": 0, "spring": 0, "summer": 0, "fall": 0}
    by_year:   dict[str, int] = {}
    total = 0
    for s in rows:
        total += 1
        h = s.get("hour")
        if h is not None:
            by_hour[int(h)] += 1
        d = s.get("day_of_week")
        if d is not None:
            by_dow[int(d)] += 1
        season = s.get("season")
        if season and season in by_season:
            by_season[season] += 1
        year = s.get("year")
        if year is not None:
            by_year[str(year)] = by_year.get(str(year), 0) + 1
    return {
        "byHour": by_hour, "byDow": by_dow,
        "bySeason": by_season, "byYear": by_year, "total": total,
    }


def main() -> None:
    if not TRACKS_PATH.exists():
        print(f"ERROR: {TRACKS_PATH} not found — run the pipeline first.")
        sys.exit(1)

    print(f"Reading {TRACKS_PATH} …")
    tracks = read_jsonl(TRACKS_PATH)

    scrobbles_agg: dict = {
        "byHour": [0] * 24, "byDow": [0] * 7,
        "bySeason": {}, "byYear": {}, "total": 0,
    }
    first_scrobbled = last_scrobbled = None

    if SCROBBLES_PATH.exists():
        print(f"Reading {SCROBBLES_PATH} …")
        scrobble_rows = read_jsonl(SCROBBLES_PATH)
        scrobbles_agg = _aggregate_scrobbles(scrobble_rows)
        dates = [r.get("scrobbled_at") for r in scrobble_rows if r.get("scrobbled_at")]
        if dates:
            first_scrobbled = min(dates)
            last_scrobbled  = max(dates)
    else:
        print(f"  (scrobbles.jsonl not found — skipping scrobble aggregation)")

    first_year = first_scrobbled[:4] if first_scrobbled else "—"
    last_year  = last_scrobbled[:4]  if last_scrobbled  else "—"
    scrobble_range = f"{first_year}–{last_year}" if first_year != "—" else "—"

    meta = {
        "isSample":      False,
        "trackCount":    len(tracks),
        "scrobbleCount": scrobbles_agg["total"],
        "scrobbleRange": scrobble_range,
        "generatedAt":   datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }

    music_data = {"meta": meta, "tracks": tracks, "scrobbles": scrobbles_agg}

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    js = (
        "// Auto-generated by scripts/generate_library_js.py — do not edit by hand.\n"
        "// Re-run the script after updating tracks.jsonl to refresh this snapshot.\n"
        "window.MUSIC_DATA = "
        + json.dumps(music_data, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
    )
    OUTPUT_PATH.write_text(js, encoding="utf-8")

    size_kb = OUTPUT_PATH.stat().st_size / 1024
    print(
        f"\nWrote {OUTPUT_PATH}\n"
        f"  {len(tracks):,} tracks · {scrobbles_agg['total']:,} scrobbles · {scrobble_range}\n"
        f"  {size_kb:.0f} KB"
    )


if __name__ == "__main__":
    main()
